# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'qmt_master:$(build.buildId)'

steps:
- script: |
    docker build -t qmt_test:latest -f Dockerfile .
    docker run qmt_test /bin/bash -c "/usr/local/envs/py27/bin/pytest /app/qmt/tests/py2.7 --junit-xml=tests2.7.xml && cat /app/tests2.7.xml" > TEST-2.7.xml
    docker run qmt_test /bin/bash -c "/usr/local/envs/py36/bin/pytest --noconftest /app/qmt/tests/py3 --junit-xml=tests3.xml && cat /app/tests3.xml" > TEST-3.xml
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'TEST-*.xml'
    testRunTitle: 'Publish test results for docker'

