# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'qmt_master:$(build.buildId)'

steps:
- script: |
    docker build -t qmt_test:latest -f Dockerfile .
    docker run qmt_test pytest --junitxml=TEST-unit_tests.xml qmt/tests/unit_tests
    docker run qmt_test cat TEST-unit_tests.xml > TEST-unit_tests.xml 
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'TEST-*.xml'
    testRunTitle: 'Publish test results for docker'

