name: py27
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - petsc=3.8.4
  - sympy=1.0
  - sphinx
  - pyside
  - pip:
    - pytest
    - mpi4py
    - shapely
    - future
    - h5py
    - holoviews
    - tqdm
    - fenics==2017.2.0
    - dask
    - dask-jobqueue
    - jupyter
